name: CI/CD pipeline
run-name: "${{ github.workflow }} - ${{ github.event_name }} - by ${{ github.actor }}"

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

permissions:
  contents: read
  packages: write

jobs:
  integration-go-test:
    name: Unit Tests for Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.x"

      - name: RUN dependencies
        run: |
          go mod download

      - name: Run Unit Tests
        run: |
          go test -v -race -cover -coverprofile=coverage.out ./internal/handlers/...

          TCOVERAGE=$(go tool cover -func=coverage.out | grep total | grep | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total Coverage is $TCOVERAGE%"

          if (( $(echo "$TCOVERAGE < 70.0" | bc -l) )); then
            echo "Test coverage ($TCOVERAGE%) is below the 70% threshold."
            exit 1
          fi
          echo "Test coverage ($TCOVERAGE%) is acceptable."

      # - name: Run Integration Tests
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     go test -v -race -cover ./internal/github/...

  integration-validate-pipeline:
    name: Validate CI/CD pipeline configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate YAML syntax
        run: |
          pip install yamllint
          yamllint -d "{extends: relaxed, rules: {line-length: disable, trailing-spaces: disable, indentation: disable, new-line-at-end-of-file: disable}}" .github/workflows/*.yml

      - name: Validate GitHub Actions workflows (actionlint) #Validate if the yaml file has no syntax errors
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color .github/workflows/*.yml

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2

  integration-go-secrets:
    name: Secret Management
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  integration-go-sast:
    name: SAST Analysis for Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.x"

      - name: Security Check with GoSec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec ./...

  integration-sca:
    name: SCA Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          ignore-unfixed: true
          format: "table"
          severity: "CRITICAL,HIGH"
          exit-code: "1"

  integration-iac-scan:
    name: IaC Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Scan k8s directory
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: k8s/
          framework: kubernetes
          soft_fail: false #

  delivery:
    name: Build Docker Image (Delivery)
    needs:
      [
        integration-go-test,
        integration-validate-pipeline,
        integration-go-secrets,
        integration-go-sast,
      ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t github-api-manager:latest .

      - name: Container Verification
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run -d --name api-go-test -p 8080:8080 -e GITHUB_TOKEN="${GITHUB_TOKEN}" github-api-manager:latest

      - name: Wait for Container to be Healthy
        run: |
          timeout=30
          elapsed=0

          until curl -fs http://localhost:8080/health > /dev/null; do
            if [ $elapsed -ge $timeout ]; then
              echo "Container did not become healthy within $timeout seconds."
              exit 1
            fi
            echo "Waiting for container to be healthy..."
            sleep 2
            elapsed=$((elapsed + 2))
          done
          echo "Container is healthy!"

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "scalabit-challenge-api:latest"
          format: "table"
          exit-code: "1" # if critical issues are found - break
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      - name: Show Container logs on failure
        if: failure()
        run: docker logs api-go-test

      - name: Stop and Remove Container
        if: always()
        run: |
          docker stop api-go-test || true
          docker rm -f api-go-test || true

  deploy:
    name: Deploy to Production
    needs: [delivery]
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Start Minicube
        uses: medyagh/setup-minikube@latest

      - name: RUN Image Builder
        run: |
          eval $(minikube docker-env)
          docker build -t scalabit-challenge-api:latest .

      - name: Kubernets Secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          kubectl create secret generic github-token --from-literal=GITHUB-TOKEN="${GITHUB_TOKEN}" \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernets
        run: kubectl apply -f k8s/

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/scalabit-challenge-api --timeout=90s || (kubectl get pods && kubectl logs -l app=scalabit-challenge-api && exit 1)

      - name: Show Status
        if: always()
        run: |
          kubectl get pods
          kubectl get services

      - name: Run Smoke Tests against Minikube
        run: |
          echo "Starting smoke tests..."
          SERVICE_URL=$(minikube service scalabit-challenge-api --url)
          echo "Testing endpoint: $SERVICE_URL/health"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --retry 5 --retry-delay 5 --retry-connrefused "$SERVICE_URL/health")

          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Smoke test failed! HTTP Status: $HTTP_STATUS"
            exit 1
          fi
          echo "Smoke test passed! Application is live and healthy."
